### ISSUE TITLE
Shibboleth Auth

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/DukeDSHandoverService#31]
Right now anyone can accept the handover.
We should add a netid/password prompt(Shibboleth).
Right now we are using nginx.
Based on [these docs](https://wiki.shibboleth.net/confluence/display/SHIB2/Integrating+Nginx+and+a+Shibboleth+SP+with+FastCGI) we would need this module: https://github.com/nginx-shib/nginx-http-shibboleth.

**Comment by dleehr** [comment]
This is in-progress. Infrastructure to support shibboleth in #32

**Comment by dleehr** [comment]
Also: remove gunicorn from requirements.txt
