### ISSUE TITLE
Implement mail draft

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/DukeDSHandoverService#5]
Basic workflow is this:

1. Client creates a *Draft* resource via the API
  - `curl -X POST https://server/drafts/ -d '{'project_id': '<project_uuid>', 'from_user_id': '<from_user_id>', 'to_user_id': '<to_user_id'>'}`
2. Service contacts DukeDS for the email addresses and the project name
3. Service sends an email using a template with the following values
  - `from_email`
  - `to_email`
  - `project_name`
  - `project_url`
4. Service records the action and updates the Draft status to Notified.

**Comment by johnbradley** [comment]
I'm having an issue implementing the case where the user has already sent the mail_draft and runs it again.
When sending a POST to `drafts/` I get back a 400. (Bad Request) with the following json:
```
{"non_field_errors":["The fields project_id, from_user_id, to_user_id must make a unique set."]}'
```
I would like a way to know that the draft already exists.

**Comment by johnbradley** [comment]
One possibility is to return a 303. I haven't seen an example of this before but its in this RFC:
https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

**Comment by dleehr** [comment]
Comments from PR and above have been moved to new issues
